# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb5fab7606b685707edb016f3a108cac7e4f7964069c4f898e6cc76642e2ca8c6acb2b920f985cbaf73a79de0bf627416464132524fd8d49265022c89f23365e

test:
  secret_key_base: 55755de5b93e6d1759cb546b6c936d5cc81b5a3773dd40b6ce46388c3dcd21110df851dba0302a0afe590003287a91832f56ce3055f5554e7da7fd53261daf2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
